"""Constants for product SKU management."""

from __future__ import annotations

SCHEMA_NAME = "sku_mgmt"
EXCHANGE_RATE_USD = 6.8

WORKFLOW_PLATFORM_LISTING_SUPPLEMENT = "platform_listing_supplement"

DIANXIAOMI_OBJECT_PRODUCT_SKU = "product_sku"
DIANXIAOMI_OBJECT_BUNDLE_SKU = "bundle_sku"
DIANXIAOMI_OBJECT_PLATFORM_PAIR = "platform_pair"

EXPORT_ACTION_CREATE = "create"
EXPORT_ACTION_UPDATE = "update"
EXPORT_ACTION_SKIP = "skip"
EXPORT_ACTION_MANUAL_REVIEW = "manual_review"

SYNC_STATUS_EXPORTED = "exported"

MAPPING_TARGET_PRODUCT_SKU = "product_sku"
MAPPING_TARGET_BUNDLE_SKU = "bundle_sku"

SALES_UNIT_SOURCE_PLATFORM_LISTING = "platform_listing"
SALES_UNIT_TYPE_SINGLE_PRODUCT = "single_product"
SALES_UNIT_TYPE_SAME_PRODUCT_MULTI_QTY = "same_product_multi_qty"
SALES_UNIT_TYPE_MULTI_PRODUCT_SET = "multi_product_set"

SOURCE_STATUS_ACTIVE = "active"
SOURCE_PLATFORM_1688 = "1688"
SOURCE_PLATFORM_TAOBAO = "taobao"
SOURCE_PLATFORM_TMALL = "tmall"
SOURCE_PLATFORM_OTHER = "other"
